// Strava proxy for the Tokyo lead-up page. Served by CloudFront on /api/* via a
// Lambda function URL (IAM auth + Origin Access Control), so the page calls it
// same-origin and nothing secret ever reaches the browser.
//
// SSM parameters (under PARAM_PREFIX, default /marathon):
//   strava/client_id      SecureString  set by deploy.sh
//   strava/client_secret  SecureString  set by deploy.sh
//   session_secret        SecureString  generated by deploy.sh
//   strava/refresh_token  SecureString  written here after OAuth
//   strava/athlete_id     String        written here on first connect; locks the app to one athlete
//   public_url            String        https://<cloudfront domain>, written by CDK
import { GetParametersCommand, PutParameterCommand, SSMClient } from "@aws-sdk/client-ssm";
import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { LambdaFunctionURLEvent, LambdaFunctionURLResult } from "aws-lambda";

type Result = Exclude<LambdaFunctionURLResult, string>;

const PREFIX = process.env.PARAM_PREFIX ?? "/marathon";
const P = {
  clientId: `${PREFIX}/strava/client_id`,
  clientSecret: `${PREFIX}/strava/client_secret`,
  refreshToken: `${PREFIX}/strava/refresh_token`,
  athleteId: `${PREFIX}/strava/athlete_id`,
  sessionSecret: `${PREFIX}/session_secret`,
  publicUrl: `${PREFIX}/public_url`,
} as const;
type Key = keyof typeof P;
type Config = Partial<Record<Key, string>>;

const STRAVA = "https://www.strava.com";
const SESSION_COOKIE = "__Host-session";
const STATE_COOKIE = "__Host-oauth_state";
const SESSION_TTL_S = 60 * 60 * 24 * 60; // 60 days
const CACHE_TTL_MS = 5 * 60 * 1000;
const CONFIG_TTL_MS = 5 * 60 * 1000;
const MAX_PAGES = 5; // 500 activities covers the predictor's ~15 months of history

// ---------- parameter store (replaceable in tests) ----------

const ssm = new SSMClient({});
export const store = {
  async get(names: string[]): Promise<Record<string, string>> {
    const out = await ssm.send(new GetParametersCommand({ Names: names, WithDecryption: true }));
    const r: Record<string, string> = {};
    for (const p of out.Parameters ?? []) if (p.Name && p.Value != null) r[p.Name] = p.Value;
    return r;
  },
  async put(name: string, value: string, secure: boolean): Promise<void> {
    await ssm.send(new PutParameterCommand({ Name: name, Value: value, Type: secure ? "SecureString" : "String", Overwrite: true }));
  },
};

let config: Config = {};
let configLoadedAt = 0;
async function loadConfig(force = false): Promise<Config> {
  if (!force && Date.now() - configLoadedAt < CONFIG_TTL_MS) return config;
  const raw = await store.get(Object.values(P));
  config = {};
  for (const k of Object.keys(P) as Key[]) if (raw[P[k]]) config[k] = raw[P[k]];
  configLoadedAt = Date.now();
  return config;
}
async function saveConfig(k: Key, value: string, secure: boolean) {
  await store.put(P[k], value, secure);
  config[k] = value;
}

// In-memory state for a warm container. Single user, so one token and a small cache.
let accessToken: { token: string; expiresAt: number } | null = null;
const cache = new Map<string, { at: number; body: string }>();

export function resetForTests() {
  config = {};
  configLoadedAt = 0;
  accessToken = null;
  cache.clear();
}

// ---------- cookies ----------

function b64url(buf: Buffer) {
  return buf.toString("base64url");
}
function hmac(secret: string, data: string) {
  return b64url(createHmac("sha256", secret).update(data).digest());
}
function safeEqual(a: string, b: string) {
  const x = Buffer.from(a), y = Buffer.from(b);
  return x.length === y.length && timingSafeEqual(x, y);
}

export function signSession(secret: string, athleteId: string, nowS = Math.floor(Date.now() / 1000)) {
  const payload = `${athleteId}.${nowS + SESSION_TTL_S}`;
  return `${payload}.${hmac(secret, payload)}`;
}

/** Returns the athlete id if the cookie is authentic and unexpired. */
export function verifySession(secret: string, value: string | undefined, nowS = Math.floor(Date.now() / 1000)) {
  if (!value) return null;
  const parts = value.split(".");
  if (parts.length !== 3) return null;
  const [athleteId, exp, sig] = parts;
  if (!safeEqual(sig, hmac(secret, `${athleteId}.${exp}`))) return null;
  if (!(Number(exp) > nowS)) return null;
  return athleteId;
}

function readCookies(event: LambdaFunctionURLEvent): Record<string, string> {
  const list = event.cookies ?? (event.headers?.cookie ? event.headers.cookie.split(/;\s*/) : []);
  const out: Record<string, string> = {};
  for (const c of list) {
    const i = c.indexOf("=");
    if (i > 0) out[c.slice(0, i).trim()] = decodeURIComponent(c.slice(i + 1).trim());
  }
  return out;
}

function cookie(name: string, value: string, maxAge: number) {
  return `${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;
}

// ---------- responses ----------

function json(status: number, body: unknown, extra: Partial<Result> = {}): Result {
  return {
    statusCode: status,
    headers: { "content-type": "application/json", "cache-control": "no-store", ...extra.headers },
    body: typeof body === "string" ? body : JSON.stringify(body),
    cookies: extra.cookies,
  };
}
function redirect(location: string, cookies?: string[]): Result {
  return { statusCode: 302, headers: { location, "cache-control": "no-store" }, cookies, body: "" };
}
function text(status: number, message: string): Result {
  return { statusCode: status, headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" }, body: message };
}

class HttpError extends Error {
  constructor(public status: number, public code: string, message: string) {
    super(message);
  }
}

// ---------- Strava ----------

type TokenResponse = {
  access_token: string;
  refresh_token: string;
  expires_at: number;
  athlete?: { id: number };
};

async function tokenRequest(params: Record<string, string>): Promise<TokenResponse> {
  const res = await fetch(`${STRAVA}/oauth/token`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(params),
  });
  if (res.status === 400 || res.status === 401) throw new HttpError(401, "not_connected", "Strava rejected the stored authorisation. Connect Strava again.");
  if (!res.ok) throw new HttpError(502, "strava_error", `Strava token endpoint returned ${res.status}.`);
  return (await res.json()) as TokenResponse;
}

async function getAccessToken(cfg: Config): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  if (accessToken && accessToken.expiresAt - 120 > now) return accessToken.token;
  if (!cfg.refreshToken) throw new HttpError(401, "not_connected", "Strava isn't connected yet.");
  const t = await tokenRequest({
    client_id: cfg.clientId!,
    client_secret: cfg.clientSecret!,
    grant_type: "refresh_token",
    refresh_token: cfg.refreshToken,
  });
  // Strava may rotate the refresh token; always keep the newest one.
  if (t.refresh_token && t.refresh_token !== cfg.refreshToken) await saveConfig("refreshToken", t.refresh_token, true);
  accessToken = { token: t.access_token, expiresAt: t.expires_at };
  return t.access_token;
}

type StravaActivity = {
  id: number;
  name: string;
  sport_type: string;
  start_date_local: string;
  distance: number;
  moving_time: number;
  total_elevation_gain?: number;
  timezone?: string; // e.g. "(GMT+10:00) Australia/Sydney"
};

export function mapActivity(a: StravaActivity) {
  return {
    id: a.id,
    name: a.name,
    sport_type: a.sport_type,
    start_local: a.start_date_local,
    tz: a.timezone?.split(" ").pop() ?? null,
    summary: { distance: a.distance, moving_time: a.moving_time, elevation_gain: a.total_elevation_gain ?? 0 },
  };
}

export function parseRange(q: Record<string, string | undefined> | undefined) {
  const after = Date.parse(q?.after ?? "");
  const before = Date.parse(q?.before ?? "");
  if (Number.isNaN(after) || Number.isNaN(before)) throw new HttpError(400, "bad_request", "after and before must be ISO 8601 date-times.");
  if (before <= after) throw new HttpError(400, "bad_request", "before must be later than after.");
  if (before - after > 460 * 86400_000) throw new HttpError(400, "bad_request", "Range is limited to about 15 months.");
  return { after: Math.floor(after / 1000), before: Math.ceil(before / 1000) };
}

async function listActivities(token: string, after: number, before: number) {
  const all: StravaActivity[] = [];
  for (let page = 1; page <= MAX_PAGES; page++) {
    const url = `${STRAVA}/api/v3/athlete/activities?after=${after}&before=${before}&per_page=100&page=${page}`;
    const res = await fetch(url, { headers: { authorization: `Bearer ${token}` } });
    if (res.status === 401) {
      accessToken = null;
      throw new HttpError(401, "not_connected", "Strava rejected the access token. Connect Strava again.");
    }
    if (res.status === 429) throw new HttpError(503, "rate_limited", "Strava's rate limit was hit. Try again in 15 minutes.");
    if (!res.ok) throw new HttpError(502, "strava_error", `Strava returned ${res.status}.`);
    const batch = (await res.json()) as StravaActivity[];
    all.push(...batch);
    if (batch.length < 100) break;
  }
  return all;
}

// ---------- routes ----------

function requireStravaApp(cfg: Config) {
  if (!cfg.clientId || !cfg.clientSecret || !cfg.sessionSecret || !cfg.publicUrl)
    throw new HttpError(500, "not_configured", "Strava app credentials aren't set in Parameter Store. Run deploy.sh.");
}

async function authStart(): Promise<Result> {
  const cfg = await loadConfig();
  requireStravaApp(cfg);
  const state = b64url(randomBytes(24));
  const q = new URLSearchParams({
    client_id: cfg.clientId!,
    redirect_uri: `${cfg.publicUrl}/api/auth/callback`,
    response_type: "code",
    approval_prompt: "auto",
    scope: "activity:read_all",
    state,
  });
  return redirect(`${STRAVA}/oauth/authorize?${q}`, [cookie(STATE_COOKIE, state, 600)]);
}

async function authCallback(event: LambdaFunctionURLEvent): Promise<Result> {
  const cfg = await loadConfig(true);
  requireStravaApp(cfg);
  const q = event.queryStringParameters ?? {};
  const clearState = cookie(STATE_COOKIE, "", 0);
  if (q.error) return text(400, `Strava authorisation was not granted (${q.error}).`);
  const expected = readCookies(event)[STATE_COOKIE];
  if (!q.state || !expected || !safeEqual(q.state, expected)) return text(400, "OAuth state didn't match. Start again from the page.");
  if (!q.code) return text(400, "Missing authorisation code.");
  if (!(q.scope ?? "").split(",").includes("activity:read_all"))
    return text(400, "The page needs the \"View data about your private activities\" permission. Start again and leave it ticked.");

  const t = await tokenRequest({
    client_id: cfg.clientId!,
    client_secret: cfg.clientSecret!,
    code: q.code,
    grant_type: "authorization_code",
  });
  const athlete = String(t.athlete?.id ?? "");
  if (!athlete) return text(502, "Strava didn't return an athlete.");
  // Single user: the first athlete to connect owns this deployment.
  if (cfg.athleteId && cfg.athleteId !== athlete) return text(403, "This deployment is linked to a different Strava athlete.");
  if (!cfg.athleteId) await saveConfig("athleteId", athlete, false);
  await saveConfig("refreshToken", t.refresh_token, true);
  accessToken = { token: t.access_token, expiresAt: t.expires_at };
  cache.clear();

  return redirect("/", [cookie(SESSION_COOKIE, signSession(cfg.sessionSecret!, athlete), SESSION_TTL_S), clearState]);
}

async function activities(event: LambdaFunctionURLEvent): Promise<Result> {
  const cfg = await loadConfig();
  requireStravaApp(cfg);
  // Public by choice: once the owner has connected, anyone with the page sees the
  // runs (name, type, date, timezone, distance, moving time, elevation gain). No session needed.
  if (!cfg.athleteId || !cfg.refreshToken) return json(401, { error: "not_connected", message: "Connect Strava to see your runs." });

  const { after, before } = parseRange(event.queryStringParameters);
  const key = `${after}:${before}`;
  const hit = cache.get(key);
  const headers = { "cache-control": "private, max-age=300" };
  if (hit && Date.now() - hit.at < CACHE_TTL_MS) return json(200, hit.body, { headers });

  const token = await getAccessToken(cfg);
  const list = await listActivities(token, after, before);
  const body = JSON.stringify({ activities: list.map(mapActivity), fetched_at: new Date().toISOString() });
  cache.set(key, { at: Date.now(), body });
  for (const [k, v] of cache) if (Date.now() - v.at >= CACHE_TTL_MS) cache.delete(k);
  return json(200, body, { headers });
}

export async function handler(event: LambdaFunctionURLEvent): Promise<Result> {
  const method = event.requestContext?.http?.method ?? "GET";
  const path = event.rawPath ?? "/";
  try {
    if (method !== "GET") return json(405, { error: "method_not_allowed" });
    if (path === "/api/auth/start") return await authStart();
    if (path === "/api/auth/callback") return await authCallback(event);
    if (path === "/api/activities") return await activities(event);
    return json(404, { error: "not_found" });
  } catch (err) {
    if (err instanceof HttpError) return json(err.status, { error: err.code, message: err.message });
    console.error(err);
    return json(500, { error: "internal", message: "Something went wrong on the server." });
  }
}
